apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
  labels:
    app: orders
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: agarwalconsulting/rvstore-order-api:v2
        ports:
        - containerPort: 9002
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 500m
            memory: 100Mi
        env:
        - name: MONGO_DB_URL
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: connection

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: rvstore-order-api
  name: rvstore-order-api
spec:
  ports:
  - port: 9002
    targetPort: 9002
  selector:
    app: orders
