apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  username: bW9uZ29hZG1pbg==
  password: c2VjcmV0
  connection: bW9uZ29kYjovL21vbmdvYWRtaW46c2VjcmV0QG1vbmdvZGItc2VydmljZS9hZG1pbg==

## Encoded using `echo -n <text> | base64`
## Decoded using `echo <secret-text> | base64 --decode`
