apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "l3-rule"
spec:
  endpointSelector:
      matchLabels: {}
  ingress:
    - fromEndpoints:
      - {}
  egress:
    - toEndpoints:
      - {}
