# Values: https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/values.yaml

prometheus:
  enabled: true

operator:
  enabled: true

  prometheus:
    enabled: true

hubble:
  enabled: true
  metrics:
    # enabled:
    #   - dns
    #   - drop
    #   - tcp
    #   - flow
    #   - icmp
    #   - http
      # - dns:query;ignoreAAAA
    enabled: ~

  relay:
    enabled: true

  ui:
    enabled: true
