kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-local-egress
spec:
  podSelector: {} # Select all pods in current namespace
  policyTypes:
    - Egress
  egress:
  - to:
    - namespaceSelector: {} # They can connect to all the pods namespaces

# This blocks all external traffic
