kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: frontend-with-dns
spec:
  podSelector:
    matchLabels:
      tier: frontend
  policyTypes:
    - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          tier: backend

    - ports:
      - port: 53
        protocol: "UDP"
      - port: 53
        protocol: "TCP"
