kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: prod-storage
  name: allow-prod-apps
spec:
  podSelector: {}
  ingress:
    - from:
      - namespaceSelector:
        matchLabels:
          purpose: prod

---

apiVersion: v1
kind: Namespace
metadata:
  name: foo-prod
  labels:
    purpose: prod
    product: foo
